ar600:
  # Publish all joint states -----------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  
  # Position Controllers --------------------------------
  
  # Hand Controllers

  # Left hand
  torso_left_shoulder_position_controller:
    type: effort_controllers/JointPositionController
    joint: torso_left_shoulder
    pid: {p: 100.0, i: 0.01, d: 10.0}


  left_upper_forearm_shoulder_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_upper_forearm_shoulder
    pid: {p: 100.0, i: 0.01, d: 10.0}

  left_upper_forearm_left_lower_forearm_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_upper_forearm_left_lower_forearm
    pid: {p: 100.0, i: 0.01, d: 10.0}

  left_lower_forearm_arm_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_lower_forearm_arm
    pid: {p: 100.0, i: 0.01, d: 10.0}

  left_lower_arm_effector_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_lower_arm_effector
    pid: {p: 100.0, i: 0.01, d: 10.0}


# Right hand
  torso_right_shoulder_position_controller:
    type: effort_controllers/JointPositionController
    joint: torso_right_shoulder
    pid: {p: 100.0, i: 0.01, d: 10.0}


  right_upper_forearm_shoulder_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_upper_forearm_shoulder
    pid: {p: 100.0, i: 0.01, d: 10.0}

  right_upper_forearm_right_lower_forearm_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_upper_forearm_right_lower_forearm
    pid: {p: 100.0, i: 0.01, d: 10.0}

  right_lower_forearm_arm_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_lower_forearm_arm
    pid: {p: 100.0, i: 0.01, d: 10.0}

  right_lower_arm_effector_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_lower_arm_effector
    pid: {p: 100.0, i: 0.01, d: 10.0}

# Legs Controllers

# Left leg
  base_left_leg_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_left_leg_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  left_base_mount_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_base_mount
    pid: {p: 100.0, i: 0.01, d: 10.0}


  left_base_mount_hip_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_base_mount_hip
    pid: {p: 100.0, i: 0.01, d: 10.0}

  left_hip_left_shin_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_hip_left_shin
    pid: {p: 100.0, i: 0.01, d: 10.0}

  left_shin_left_foot_mount_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_shin_left_foot_mount
    pid: {p: 100.0, i: 0.01, d: 10.0}

  left_shin_mount_left_foot_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_shin_mount_left_foot
    pid: {p: 100.0, i: 0.01, d: 10.0}

# Right leg
  base_right_leg_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_right_leg_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  right_base_mount_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_base_mount
    pid: {p: 100.0, i: 0.01, d: 10.0}


  right_base_mount_hip_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_base_mount_hip
    pid: {p: 100.0, i: 0.01, d: 10.0}

  right_hip_right_shin_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_hip_right_shin
    pid: {p: 100.0, i: 0.01, d: 10.0}

  right_shin_right_foot_mount_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_shin_right_foot_mount
    pid: {p: 100.0, i: 0.01, d: 10.0}

  right_shin_mount_right_foot_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_shin_mount_right_foot
    pid: {p: 100.0, i: 0.01, d: 10.0}


  # Torso

  torso_rotation_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: torso_rotation_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}


  # Head

  torso_head_mount_position_controller:
    type: effort_controllers/JointPositionController
    joint: torso_head_mount
    pid: {p: 100.0, i: 0.01, d: 10.0}

  mount_head_tilt_mount_position_controller:
    type: effort_controllers/JointPositionController
    joint: mount_head_tilt_mount
    pid: {p: 100.0, i: 0.01, d: 10.0}

  head_mount_head_position_controller:
    type: effort_controllers/JointPositionController
    joint: head_mount_head
    pid: {p: 100.0, i: 0.01, d: 10.0}